// src/constants/cookBatchConstants.js

// LIST batches
export const COOKBATCH_LIST_REQUEST = "COOKBATCH_LIST_REQUEST";
export const COOKBATCH_LIST_SUCCESS = "COOKBATCH_LIST_SUCCESS";
export const COOKBATCH_LIST_FAIL = "COOKBATCH_LIST_FAIL";
export const COOKBATCH_LIST_RESET = "COOKBATCH_LIST_RESET";

// CREATE batch (prediction run)
export const COOKBATCH_CREATE_REQUEST = "COOKBATCH_CREATE_REQUEST";
export const COOKBATCH_CREATE_SUCCESS = "COOKBATCH_CREATE_SUCCESS";
export const COOKBATCH_CREATE_FAIL = "COOKBATCH_CREATE_FAIL";
export const COOKBATCH_CREATE_RESET = "COOKBATCH_CREATE_RESET";

// DETAIL batch
export const COOKBATCH_DETAIL_REQUEST = "COOKBATCH_DETAIL_REQUEST";
export const COOKBATCH_DETAIL_SUCCESS = "COOKBATCH_DETAIL_SUCCESS";
export const COOKBATCH_DETAIL_FAIL = "COOKBATCH_DETAIL_FAIL";
export const COOKBATCH_DETAIL_RESET = "COOKBATCH_DETAIL_RESET";

// PATCH actuals / finalize
export const COOKBATCH_ACTUALS_UPDATE_REQUEST =
  "COOKBATCH_ACTUALS_UPDATE_REQUEST";
export const COOKBATCH_ACTUALS_UPDATE_SUCCESS =
  "COOKBATCH_ACTUALS_UPDATE_SUCCESS";
export const COOKBATCH_ACTUALS_UPDATE_FAIL = "COOKBATCH_ACTUALS_UPDATE_FAIL";
export const COOKBATCH_ACTUALS_UPDATE_RESET = "COOKBATCH_ACTUALS_UPDATE_RESET";

// LIST recipes (for dropdown/select)
export const RECIPE_LIST_REQUEST = "RECIPE_LIST_REQUEST";
export const RECIPE_LIST_SUCCESS = "RECIPE_LIST_SUCCESS";
export const RECIPE_LIST_FAIL = "RECIPE_LIST_FAIL";
export const RECIPE_LIST_RESET = "RECIPE_LIST_RESET";

// RECALIBRATION
export const RECALIBRATE_REQUEST = "RECALIBRATE_REQUEST";
export const RECALIBRATE_SUCCESS = "RECALIBRATE_SUCCESS";
export const RECALIBRATE_FAIL = "RECALIBRATE_FAIL";
export const RECALIBRATE_RESET = "RECALIBRATE_RESET";

//
export const USER_ME_REQUEST = "USER_ME_REQUEST";
export const USER_ME_SUCCESS = "USER_ME_SUCCESS";
export const USER_ME_FAIL = "USER_ME_FAIL";

//Admin Ui Management
//
export const ACCOUNT_ME_REQUEST = "ACCOUNT_ME_REQUEST";
export const ACCOUNT_ME_SUCCESS = "ACCOUNT_ME_SUCCESS";
export const ACCOUNT_ME_FAIL = "ACCOUNT_ME_FAIL";
export const ACCOUNT_ME_RESET = "ACCOUNT_ME_RESET";

//
export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

//
export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";
export const USER_CREATE_RESET = "USER_CREATE_RESET";

//
export const USER_ROLE_UPDATE_REQUEST = "USER_ROLE_UPDATE_REQUEST";
export const USER_ROLE_UPDATE_SUCCESS = "USER_ROLE_UPDATE_SUCCESS";
export const USER_ROLE_UPDATE_FAIL = "USER_ROLE_UPDATE_FAIL";
export const USER_ROLE_UPDATE_RESET = "USER_ROLE_UPDATE_RESET";
