// src/constants/cookBatchConstants.js

// LIST batches
export const COOKBATCH_LIST_REQUEST = "COOKBATCH_LIST_REQUEST";
export const COOKBATCH_LIST_SUCCESS = "COOKBATCH_LIST_SUCCESS";
export const COOKBATCH_LIST_FAIL = "COOKBATCH_LIST_FAIL";
export const COOKBATCH_LIST_RESET = "COOKBATCH_LIST_RESET";

// CREATE batch (prediction run)
export const COOKBATCH_CREATE_REQUEST = "COOKBATCH_CREATE_REQUEST";
export const COOKBATCH_CREATE_SUCCESS = "COOKBATCH_CREATE_SUCCESS";
export const COOKBATCH_CREATE_FAIL = "COOKBATCH_CREATE_FAIL";
export const COOKBATCH_CREATE_RESET = "COOKBATCH_CREATE_RESET";

// DETAIL batch
export const COOKBATCH_DETAIL_REQUEST = "COOKBATCH_DETAIL_REQUEST";
export const COOKBATCH_DETAIL_SUCCESS = "COOKBATCH_DETAIL_SUCCESS";
export const COOKBATCH_DETAIL_FAIL = "COOKBATCH_DETAIL_FAIL";
export const COOKBATCH_DETAIL_RESET = "COOKBATCH_DETAIL_RESET";

// PATCH actuals / finalize
export const COOKBATCH_ACTUALS_UPDATE_REQUEST =
  "COOKBATCH_ACTUALS_UPDATE_REQUEST";
export const COOKBATCH_ACTUALS_UPDATE_SUCCESS =
  "COOKBATCH_ACTUALS_UPDATE_SUCCESS";
export const COOKBATCH_ACTUALS_UPDATE_FAIL = "COOKBATCH_ACTUALS_UPDATE_FAIL";
export const COOKBATCH_ACTUALS_UPDATE_RESET = "COOKBATCH_ACTUALS_UPDATE_RESET";

// LIST recipes (for dropdown/select)
export const RECIPE_LIST_REQUEST = "RECIPE_LIST_REQUEST";
export const RECIPE_LIST_SUCCESS = "RECIPE_LIST_SUCCESS";
export const RECIPE_LIST_FAIL = "RECIPE_LIST_FAIL";
export const RECIPE_LIST_RESET = "RECIPE_LIST_RESET";

// LIST protein choices (for dropdown/select)
export const PROTEIN_CHOICE_LIST_REQUEST = "PROTEIN_CHOICE_LIST_REQUEST";
export const PROTEIN_CHOICE_LIST_SUCCESS = "PROTEIN_CHOICE_LIST_SUCCESS";
export const PROTEIN_CHOICE_LIST_FAIL = "PROTEIN_CHOICE_LIST_FAIL";
export const PROTEIN_CHOICE_LIST_RESET = "PROTEIN_CHOICE_LIST_RESET";

// POST-REVIEW UPDATE (finalized batches only)
export const COOKBATCH_POST_REVIEW_REQUEST = "COOKBATCH_POST_REVIEW_REQUEST";
export const COOKBATCH_POST_REVIEW_SUCCESS = "COOKBATCH_POST_REVIEW_SUCCESS";
export const COOKBATCH_POST_REVIEW_FAIL = "COOKBATCH_POST_REVIEW_FAIL";
export const COOKBATCH_POST_REVIEW_RESET = "COOKBATCH_POST_REVIEW_RESET";

// RECALIBRATION
export const RECALIBRATE_REQUEST = "RECALIBRATE_REQUEST";
export const RECALIBRATE_SUCCESS = "RECALIBRATE_SUCCESS";
export const RECALIBRATE_FAIL = "RECALIBRATE_FAIL";
export const RECALIBRATE_RESET = "RECALIBRATE_RESET";

//
export const USER_ME_REQUEST = "USER_ME_REQUEST";
export const USER_ME_SUCCESS = "USER_ME_SUCCESS";
export const USER_ME_FAIL = "USER_ME_FAIL";

//Admin Ui Management
//
export const ACCOUNT_ME_REQUEST = "ACCOUNT_ME_REQUEST";
export const ACCOUNT_ME_SUCCESS = "ACCOUNT_ME_SUCCESS";
export const ACCOUNT_ME_FAIL = "ACCOUNT_ME_FAIL";
export const ACCOUNT_ME_RESET = "ACCOUNT_ME_RESET";

//
export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

//
export const USER_ROLE_UPDATE_REQUEST = "USER_ROLE_UPDATE_REQUEST";
export const USER_ROLE_UPDATE_SUCCESS = "USER_ROLE_UPDATE_SUCCESS";
export const USER_ROLE_UPDATE_FAIL = "USER_ROLE_UPDATE_FAIL";
export const USER_ROLE_UPDATE_RESET = "USER_ROLE_UPDATE_RESET";

//
export const BRANCH_LIST_REQUEST = "BRANCH_LIST_REQUEST";
export const BRANCH_LIST_SUCCESS = "BRANCH_LIST_SUCCESS";
export const BRANCH_LIST_FAIL = "BRANCH_LIST_FAIL";
export const BRANCH_LIST_RESET = "BRANCH_LIST_RESET";

//
// Branch Manager - staff list
export const BRANCH_MANAGER_STAFF_LIST_REQUEST =
  "BRANCH_MANAGER_STAFF_LIST_REQUEST";
export const BRANCH_MANAGER_STAFF_LIST_SUCCESS =
  "BRANCH_MANAGER_STAFF_LIST_SUCCESS";
export const BRANCH_MANAGER_STAFF_LIST_FAIL = "BRANCH_MANAGER_STAFF_LIST_FAIL";
export const BRANCH_MANAGER_STAFF_LIST_RESET =
  "BRANCH_MANAGER_STAFF_LIST_RESET";

//
// Branch Manager - branches
export const BRANCH_MANAGER_BRANCH_LIST_REQUEST =
  "BRANCH_MANAGER_BRANCH_LIST_REQUEST";
export const BRANCH_MANAGER_BRANCH_LIST_SUCCESS =
  "BRANCH_MANAGER_BRANCH_LIST_SUCCESS";
export const BRANCH_MANAGER_BRANCH_LIST_FAIL =
  "BRANCH_MANAGER_BRANCH_LIST_FAIL";
export const BRANCH_MANAGER_BRANCH_LIST_RESET =
  "BRANCH_MANAGER_BRANCH_LIST_RESET";

//
// Branch Manager - user search
export const BRANCH_MANAGER_USER_SEARCH_REQUEST =
  "BRANCH_MANAGER_USER_SEARCH_REQUEST";
export const BRANCH_MANAGER_USER_SEARCH_SUCCESS =
  "BRANCH_MANAGER_USER_SEARCH_SUCCESS";
export const BRANCH_MANAGER_USER_SEARCH_FAIL =
  "BRANCH_MANAGER_USER_SEARCH_FAIL";
export const BRANCH_MANAGER_USER_SEARCH_RESET =
  "BRANCH_MANAGER_USER_SEARCH_RESET";

//
// Branch Manager - create assignment
export const BRANCH_MANAGER_ASSIGNMENT_CREATE_REQUEST =
  "BRANCH_MANAGER_ASSIGNMENT_CREATE_REQUEST";
export const BRANCH_MANAGER_ASSIGNMENT_CREATE_SUCCESS =
  "BRANCH_MANAGER_ASSIGNMENT_CREATE_SUCCESS";
export const BRANCH_MANAGER_ASSIGNMENT_CREATE_FAIL =
  "BRANCH_MANAGER_ASSIGNMENT_CREATE_FAIL";
export const BRANCH_MANAGER_ASSIGNMENT_CREATE_RESET =
  "BRANCH_MANAGER_ASSIGNMENT_CREATE_RESET";

//
// Branch Manager - update assignment
export const BRANCH_MANAGER_ASSIGNMENT_UPDATE_REQUEST =
  "BRANCH_MANAGER_ASSIGNMENT_UPDATE_REQUEST";
export const BRANCH_MANAGER_ASSIGNMENT_UPDATE_SUCCESS =
  "BRANCH_MANAGER_ASSIGNMENT_UPDATE_SUCCESS";
export const BRANCH_MANAGER_ASSIGNMENT_UPDATE_FAIL =
  "BRANCH_MANAGER_ASSIGNMENT_UPDATE_FAIL";
export const BRANCH_MANAGER_ASSIGNMENT_UPDATE_RESET =
  "BRANCH_MANAGER_ASSIGNMENT_UPDATE_RESET";

//
// Branch Manager - delete assignment
export const BRANCH_MANAGER_ASSIGNMENT_DELETE_REQUEST =
  "BRANCH_MANAGER_ASSIGNMENT_DELETE_REQUEST";
export const BRANCH_MANAGER_ASSIGNMENT_DELETE_SUCCESS =
  "BRANCH_MANAGER_ASSIGNMENT_DELETE_SUCCESS";
export const BRANCH_MANAGER_ASSIGNMENT_DELETE_FAIL =
  "BRANCH_MANAGER_ASSIGNMENT_DELETE_FAIL";
export const BRANCH_MANAGER_ASSIGNMENT_DELETE_RESET =
  "BRANCH_MANAGER_ASSIGNMENT_DELETE_RESET";

// RECIPE MANAGEMENT
export const RECIPE_DETAIL_REQUEST = "RECIPE_DETAIL_REQUEST";
export const RECIPE_DETAIL_SUCCESS = "RECIPE_DETAIL_SUCCESS";
export const RECIPE_DETAIL_FAIL = "RECIPE_DETAIL_FAIL";
export const RECIPE_DETAIL_RESET = "RECIPE_DETAIL_RESET";

export const RECIPE_CREATE_REQUEST = "RECIPE_CREATE_REQUEST";
export const RECIPE_CREATE_SUCCESS = "RECIPE_CREATE_SUCCESS";
export const RECIPE_CREATE_FAIL = "RECIPE_CREATE_FAIL";
export const RECIPE_CREATE_RESET = "RECIPE_CREATE_RESET";

export const RECIPE_UPDATE_REQUEST = "RECIPE_UPDATE_REQUEST";
export const RECIPE_UPDATE_SUCCESS = "RECIPE_UPDATE_SUCCESS";
export const RECIPE_UPDATE_FAIL = "RECIPE_UPDATE_FAIL";
export const RECIPE_UPDATE_RESET = "RECIPE_UPDATE_RESET";

export const RECIPE_DELETE_REQUEST = "RECIPE_DELETE_REQUEST";
export const RECIPE_DELETE_SUCCESS = "RECIPE_DELETE_SUCCESS";
export const RECIPE_DELETE_FAIL = "RECIPE_DELETE_FAIL";
export const RECIPE_DELETE_RESET = "RECIPE_DELETE_RESET";

// RECIPE INGREDIENT MANAGEMENT
export const RECIPE_INGREDIENT_LIST_REQUEST = "RECIPE_INGREDIENT_LIST_REQUEST";
export const RECIPE_INGREDIENT_LIST_SUCCESS = "RECIPE_INGREDIENT_LIST_SUCCESS";
export const RECIPE_INGREDIENT_LIST_FAIL = "RECIPE_INGREDIENT_LIST_FAIL";
export const RECIPE_INGREDIENT_LIST_RESET = "RECIPE_INGREDIENT_LIST_RESET";

export const RECIPE_INGREDIENT_CREATE_REQUEST =
  "RECIPE_INGREDIENT_CREATE_REQUEST";
export const RECIPE_INGREDIENT_CREATE_SUCCESS =
  "RECIPE_INGREDIENT_CREATE_SUCCESS";
export const RECIPE_INGREDIENT_CREATE_FAIL = "RECIPE_INGREDIENT_CREATE_FAIL";
export const RECIPE_INGREDIENT_CREATE_RESET = "RECIPE_INGREDIENT_CREATE_RESET";

export const RECIPE_INGREDIENT_UPDATE_REQUEST =
  "RECIPE_INGREDIENT_UPDATE_REQUEST";
export const RECIPE_INGREDIENT_UPDATE_SUCCESS =
  "RECIPE_INGREDIENT_UPDATE_SUCCESS";
export const RECIPE_INGREDIENT_UPDATE_FAIL = "RECIPE_INGREDIENT_UPDATE_FAIL";
export const RECIPE_INGREDIENT_UPDATE_RESET = "RECIPE_INGREDIENT_UPDATE_RESET";

export const RECIPE_INGREDIENT_DELETE_REQUEST =
  "RECIPE_INGREDIENT_DELETE_REQUEST";
export const RECIPE_INGREDIENT_DELETE_SUCCESS =
  "RECIPE_INGREDIENT_DELETE_SUCCESS";
export const RECIPE_INGREDIENT_DELETE_FAIL = "RECIPE_INGREDIENT_DELETE_FAIL";
export const RECIPE_INGREDIENT_DELETE_RESET = "RECIPE_INGREDIENT_DELETE_RESET";

// RECIPE CSV UPLOAD
export const RECIPE_CSV_UPLOAD_REQUEST = "RECIPE_CSV_UPLOAD_REQUEST";
export const RECIPE_CSV_UPLOAD_SUCCESS = "RECIPE_CSV_UPLOAD_SUCCESS";
export const RECIPE_CSV_UPLOAD_FAIL = "RECIPE_CSV_UPLOAD_FAIL";
export const RECIPE_CSV_UPLOAD_RESET = "RECIPE_CSV_UPLOAD_RESET";
