// src/constants/cookBatchConstants.js

// LIST batches
export const COOKBATCH_LIST_REQUEST = "COOKBATCH_LIST_REQUEST";
export const COOKBATCH_LIST_SUCCESS = "COOKBATCH_LIST_SUCCESS";
export const COOKBATCH_LIST_FAIL = "COOKBATCH_LIST_FAIL";
export const COOKBATCH_LIST_RESET = "COOKBATCH_LIST_RESET";

// CREATE batch (prediction run)
export const COOKBATCH_CREATE_REQUEST = "COOKBATCH_CREATE_REQUEST";
export const COOKBATCH_CREATE_SUCCESS = "COOKBATCH_CREATE_SUCCESS";
export const COOKBATCH_CREATE_FAIL = "COOKBATCH_CREATE_FAIL";
export const COOKBATCH_CREATE_RESET = "COOKBATCH_CREATE_RESET";

// DETAIL batch
export const COOKBATCH_DETAIL_REQUEST = "COOKBATCH_DETAIL_REQUEST";
export const COOKBATCH_DETAIL_SUCCESS = "COOKBATCH_DETAIL_SUCCESS";
export const COOKBATCH_DETAIL_FAIL = "COOKBATCH_DETAIL_FAIL";
export const COOKBATCH_DETAIL_RESET = "COOKBATCH_DETAIL_RESET";

// PATCH actuals / finalize
export const COOKBATCH_ACTUALS_UPDATE_REQUEST =
  "COOKBATCH_ACTUALS_UPDATE_REQUEST";
export const COOKBATCH_ACTUALS_UPDATE_SUCCESS =
  "COOKBATCH_ACTUALS_UPDATE_SUCCESS";
export const COOKBATCH_ACTUALS_UPDATE_FAIL = "COOKBATCH_ACTUALS_UPDATE_FAIL";
export const COOKBATCH_ACTUALS_UPDATE_RESET = "COOKBATCH_ACTUALS_UPDATE_RESET";
